// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzzqjNQNL4-Jgjq7D98Ns6sPkcZ0LkdSQ',
    appId: '1:687756687445:web:88b8e8bdae8f9c523ebcdc',
    messagingSenderId: '687756687445',
    projectId: 'griva-app-18f0f',
    authDomain: 'griva-app-18f0f.firebaseapp.com',
    storageBucket: 'griva-app-18f0f.firebasestorage.app',
    measurementId: 'G-Z88VS5RDGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmZyIcx-dMxJDLLHoazVqwaMmpPKGGhvI',
    appId: '1:687756687445:android:da419f99848eb2473ebcdc',
    messagingSenderId: '687756687445',
    projectId: 'griva-app-18f0f',
    storageBucket: 'griva-app-18f0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk_ZWBlhPU3l1zscUtEkV2m1E5bbMI_sE',
    appId: '1:687756687445:ios:f8a17b69b095cae13ebcdc',
    messagingSenderId: '687756687445',
    projectId: 'griva-app-18f0f',
    storageBucket: 'griva-app-18f0f.firebasestorage.app',
    iosBundleId: 'com.example.grivaPi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk_ZWBlhPU3l1zscUtEkV2m1E5bbMI_sE',
    appId: '1:687756687445:ios:f8a17b69b095cae13ebcdc',
    messagingSenderId: '687756687445',
    projectId: 'griva-app-18f0f',
    storageBucket: 'griva-app-18f0f.firebasestorage.app',
    iosBundleId: 'com.example.grivaPi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzzqjNQNL4-Jgjq7D98Ns6sPkcZ0LkdSQ',
    appId: '1:687756687445:web:2d5742fca10d21c23ebcdc',
    messagingSenderId: '687756687445',
    projectId: 'griva-app-18f0f',
    authDomain: 'griva-app-18f0f.firebaseapp.com',
    storageBucket: 'griva-app-18f0f.firebasestorage.app',
    measurementId: 'G-6VM4DXCRJ2',
  );
}
